# Generated by Django 3.1.5 on 2021-05-03 12:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='text',
        ),
        migrations.AddField(
            model_name='course',
            name='lectures',
            field=models.CharField(help_text='введіть кількість лекцій', max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(1, 'Title must be greater than 1 characters')], verbose_name='Кількість лекцій'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(help_text='введіть назву курсу', max_length=200, validators=[django.core.validators.MinLengthValidator(4, 'Title must be greater than 4 characters')], verbose_name='Назва'),
        ),
    ]
