# Generated by Django 3.1.5 on 2021-05-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210503_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='finish',
            field=models.CharField(help_text='введіть дату закінчення курсу', max_length=25, null=True, verbose_name='дата закінчення'),
        ),
        migrations.AddField(
            model_name='course',
            name='start',
            field=models.CharField(help_text='введіть дату старту курсу', max_length=25, null=True, verbose_name='дата початку'),
        ),
    ]
